project:
  type: website
  output-dir: docs  
   resources:
    - resume.pdf
    - photo.jpg

website:
  title: "Jiahe Ren"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: Resume.qmd 

format:
  html:
    theme: sandstone
    mainfont: Arial
    fontsize: 1.1rem
    linkcolor: "#0066cc"


