project:
  type: website
  output-dir: docs
  resources:
    - resume.pdf

website:
  title: "Jiahe Ren – Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Resume
        href: resume.pdf

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.2rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier new

editor: visual


